sudo: required

notifications:
  email: false

services:
  - docker

install:
  - docker build -t "swiftyninja" .

script:
  - docker run -it "swiftyinja" swift test
  - docker tag "swiftyninja" echopadder/swiftyninja
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push echopadder/swiftyninja
  - docker logout
  
